services:
  lavalink:
    image: ghcr.io/lavalink-devs/lavalink:4
    container_name: lavalink
    restart: unless-stopped
    environment:
      - SERVER_PORT=2333
      - LAVALINK_SERVER_PASSWORD=${LAVALINK_PASSWORD:-youshallnotpass}
    volumes:
      - ./application.yml:/opt/Lavalink/application.yml
      - ./plugins/:/opt/Lavalink/plugins/

  bot:
    build: .
    container_name: discord-bot
    restart: unless-stopped
    depends_on:
      - lavalink
    environment:
      - DOTNET_ENVIRONMENT=Production
      - Discord__Token=${DISCORD_TOKEN:?err}
      - Discord__OwnerId=${DISCORD_OWNER_ID:-0}
      - Lavalink__BaseAddress=http://lavalink:2333
      - Lavalink__Password=${LAVALINK_PASSWORD:-youshallnotpass}
      - Modmail__GuildId=${MODMAIL_GUILD_ID:?err}
      - Modmail__CategoryId=${MODMAIL_CATEGORY_ID:-0}
    volumes:
      - ./data:/data:Z

volumes:
  lavalink-data:
