export default {
  server: {
    host: '0.0.0.0',
    port: 2333,
    password: process.env.NODELINK_SERVER_PASSWORD || 'youshallnotpass',
    useBunServer: false,
  },
  cluster: {
    enabled: true,
    workers: 0,
    minWorkers: 1,
    runtime: {
      workerMaxOldSpaceMb: 0,
      workerExposeGc: false,
      workerExecArgv: [],
      sourceWorkerMaxOldSpaceMb: 0,
      sourceWorkerExposeGc: false,
      sourceWorkerExecArgv: [],
    },
    specializedSourceWorker: {
      enabled: true,
      count: 0,
      microWorkers: 2,
      tasksPerWorker: 128,
      silentLogs: false,
    },
    commandTimeout: 10000,
    fastCommandTimeout: 5000,
    maxRetries: 3,
    hibernation: { enabled: false, timeoutMs: 1200000 },
    scaling: {
      maxPlayersPerWorker: 200,
      targetUtilization: 0.85,
      scaleUpThreshold: 0.8,
      scaleDownThreshold: 0.2,
      checkIntervalMs: 2000,
      idleWorkerTimeoutMs: 300000,
      queueLengthScaleUpFactor: 10,
      lagPenaltyLimit: 120,
      cpuPenaltyLimit: 0.95,
    },
    endpoint: {
      patchEnabled: true,
      allowExternalPatch: false,
      code: 'CAPYBARA',
    },
  },
  logging: {
    level: 'info',
    file: {
      enabled: false,
      path: 'logs',
      rotation: 'daily',
      ttlDays: 7,
    },
    debug: {
      all: false,
      request: false,
      session: false,
      player: false,
      filters: false,
      sources: false,
      lyrics: false,
      youtube: false,
      'youtube-cipher': false,
      sabr: false,
      potoken: false,
    },
  },
  connection: {
    logAllChecks: false,
    interval: 60000,
    timeout: 5000,
    thresholds: { bad: 3, average: 10 },
  },
  maxSearchResults: 10,
  maxAlbumPlaylistLength: 100,
  playerUpdateInterval: 1000,
  statsUpdateInterval: 15000,
  trackStuckThresholdMs: 5000,
  eventTimeoutMs: 30000,
  zombieThresholdMs: 120000,
  enableHoloTracks: false,
  enableTrackStreamEndpoint: false,
  enableLoadStreamEndpoint: false,
  resolveExternalLinks: false,
  fetchChannelInfo: false,
  sponsorblock: {
    enabled: false,
    api: 'https://sponsor.ajay.app',
    categories: ['sponsor', 'selfpromo', 'interaction', 'intro', 'outro', 'preview', 'music_offtopic', 'filler'],
    actionTypes: ['skip'],
    skipMarginMs: 150,
  },
  filters: {
    enabled: {
      tremolo: false,
      vibrato: false,
      lowpass: false,
      highpass: false,
      rotation: false,
      karaoke: false,
      distortion: false,
      channelMix: false,
      equalizer: false,
      chorus: false,
      compressor: false,
      echo: false,
      phaser: false,
      timescale: false,
    },
  },
  defaultSearchSource: ['youtube', 'soundcloud'],
  unifiedSearchSources: ['youtube', 'soundcloud'],
  sources: {
    youtube: { enabled: true, allowItag: [], targetItag: null, getOAuthToken: false, hl: 'en', gl: 'US', fallbackSources: [], clients: { search: ['MUSIC_ANDROID', 'Android', 'WEB', 'TVHTML5', 'TV', 'WEB_CREATOR', 'ANDROID_TESTSUITE', 'ANDROID_VR', 'WEB_REMIX'], playback: ['MUSIC_ANDROID', 'Android', 'WEB', 'TVHTML5', 'TV', 'WEB_CREATOR', 'ANDROID_TESTSUITE', 'ANDROID_VR', 'WEB_REMIX'], resolve: ['MUSIC_ANDROID', 'Android', 'WEB', 'TVHTML5', 'TV', 'WEB_CREATOR', 'ANDROID_TESTSUITE', 'ANDROID_VR', 'WEB_REMIX'] }, cipher: { url: 'https://cipher.kikkia.dev/api', token: null } },
    http: { enabled: true, userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36' },
    soundcloud: { enabled: true },
    spotify: { enabled: false },
    applemusic: { enabled: false },
    deezer: { enabled: false },
    bandcamp: { enabled: false },
    tidal: { enabled: false },
    pandora: { enabled: false },
    qobuz: { enabled: false },
    yandexmusic: { enabled: false },
    vkmusic: { enabled: false },
    amazonmusic: { enabled: false },
    anghami: { enabled: false },
    audiomack: { enabled: false },
    audius: { enabled: false },
    bilibili: { enabled: false },
    bluesky: { enabled: false },
    eternalbox: { enabled: false },
    flowery: { enabled: false },
    gaana: { enabled: false },
    googledrive: { enabled: false },
    'google-tts': { enabled: false },
    iheartradio: { enabled: false },
    instagram: { enabled: false },
    jiosaavn: { enabled: false },
    kwai: { enabled: false },
    lastfm: { enabled: false },
    lazypytts: { enabled: false },
    letrasmus: { enabled: false },
    local: { enabled: false },
    mixcloud: { enabled: false },
    monochrome: { enabled: false },
    netease: { enabled: false },
    nicovideo: { enabled: false },
    pinterest: { enabled: false },
    pipertts: { enabled: false },
    reddit: { enabled: false },
    rss: { enabled: false },
    shazam: { enabled: false },
    songlink: { enabled: false },
    telegram: { enabled: false },
    tumblr: { enabled: false },
    twitch: { enabled: false },
    twitter: { enabled: false },
    vimeo: { enabled: false },
  },
  lyrics: { fallbackSource: 'genius', youtube: { enabled: false }, genius: { enabled: false }, musixmatch: { enabled: false }, deezer: { enabled: false }, lrclib: { enabled: false }, letrasmus: { enabled: false }, bilibili: { enabled: false }, yandexmusic: { enabled: false }, monochrome: { enabled: false } },
  meanings: { letrasmus: { enabled: false }, wikipedia: { enabled: false } },
  audio: {
    quality: 'high',
    encryption: 'aead_aes256_gcm_rtpsize',
    resamplingQuality: 'best',
    loudnessNormalizer: false,
    lookaheadMs: 5,
    gateThresholdLUFS: -60,
    fading: { enabled: false, trackStart: { duration: 0, curve: 'linear', type: 'volume' }, trackEnd: { duration: 0, curve: 'linear', type: 'volume' }, trackStop: { duration: 0, curve: 'linear', type: 'volume' }, seek: { duration: 0, curve: 'linear', type: 'volume' }, pause: { duration: 0, curve: 'sinusoidal', type: 'tape' }, resume: { duration: 0, curve: 'sinusoidal', type: 'tape' }, ducking: { enabled: false, duration: 0, targetVolume: 0.3, curve: 'linear' } },
    crossfade: { enabled: false, duration: 0, curve: 'sinusoidal', mode: 'preload', minBufferMs: 250, bufferMs: 0 },
  },
  voiceReceive: { enabled: false, format: 'opus' },
  routePlanner: { strategy: 'RotateOnBan', bannedIpCooldown: 600000, ipBlocks: [] },
  rateLimit: { enabled: false, global: { maxRequests: 10000, timeWindowMs: 60000 }, perIp: { maxRequests: 1000, timeWindowMs: 10000 }, perUserId: { maxRequests: 500, timeWindowMs: 5000 }, perGuildId: { maxRequests: 200, timeWindowMs: 5000 }, ignorePaths: [], ignore: { userIds: [], guildIds: [], ips: [] } },
  dosProtection: { enabled: false, thresholds: { burstRequests: 200, timeWindowMs: 10000 }, mitigation: { delayMs: 100, blockDurationMs: 300000 }, ignore: { userIds: [], guildIds: [], ips: [] } },
  metrics: { enabled: false, authorization: { type: 'Bearer', username: 'admin', password: '' } },
  mix: { enabled: false, defaultVolume: 0.8, maxLayersMix: 5, autoCleanup: true },
  plugins: [],
  pluginConfig: {},
};
