export default {
  server: {
    host: '0.0.0.0',
    port: 2333,
    password: process.env.NODELINK_SERVER_PASSWORD || 'youshallnotpass',
  },
  cluster: {
    enabled: true,
    workers: 0,
    minWorkers: 1,
    specializedSourceWorker: {
      enabled: true,
      count: 1,
      microWorkers: 1,
      tasksPerWorker: 32,
      silentLogs: true,
    },
    commandTimeout: 6000,
    fastCommandTimeout: 4000,
    maxRetries: 2,
    hibernation: { enabled: true, timeoutMs: 1200000 },
  },
  logging: {
    level: 'info',
    debug: { all: false, request: false, session: true, player: true, filters: false, sources: false, lyrics: false, youtube: true },
  },
  defaultSearchSource: ['youtube'],
  unifiedSearchSources: ['youtube'],
  sources: {
    youtube: { enabled: true, getOAuthToken: false, hl: 'en', gl: 'US' },
    http: { enabled: true },
    soundcloud: { enabled: false },
    spotify: { enabled: false },
    applemusic: { enabled: false },
    deezer: { enabled: false },
    bandcamp: { enabled: false },
    tidal: { enabled: false },
    pandora: { enabled: false },
    qobuz: { enabled: false },
    yandexmusic: { enabled: false },
    vkmusic: { enabled: false },
    amazonmusic: { enabled: false },
    anghami: { enabled: false },
    audiomack: { enabled: false },
    audius: { enabled: false },
    bilibili: { enabled: false },
    bluesky: { enabled: false },
    eternalbox: { enabled: false },
    flowery: { enabled: false },
    gaana: { enabled: false },
    googledrive: { enabled: false },
    'google-tts': { enabled: false },
    iheartradio: { enabled: false },
    instagram: { enabled: false },
    jiosaavn: { enabled: false },
    kwai: { enabled: false },
    lastfm: { enabled: false },
    lazypytts: { enabled: false },
    letrasmus: { enabled: false },
    local: { enabled: false },
    mixcloud: { enabled: false },
    monochrome: { enabled: false },
    netease: { enabled: false },
    nicovideo: { enabled: false },
    pinterest: { enabled: false },
    pipertts: { enabled: false },
    reddit: { enabled: false },
    rss: { enabled: false },
    shazam: { enabled: false },
    songlink: { enabled: false },
    telegram: { enabled: false },
    tumblr: { enabled: false },
    twitch: { enabled: false },
    twitter: { enabled: false },
    vimeo: { enabled: false },
  },
  lyrics: { fallbackSource: 'youtube', youtube: { enabled: true }, genius: { enabled: false }, musixmatch: { enabled: false }, deezer: { enabled: false }, lrclib: { enabled: false }, letrasmus: { enabled: false }, bilibili: { enabled: false }, yandexmusic: { enabled: false }, monochrome: { enabled: false } },
  meanings: { letrasmus: { enabled: false }, wikipedia: { enabled: false } },
  audio: { quality: 'high', encryption: 'aead_aes256_gcm_rtpsize', resamplingQuality: 'best', loudnessNormalizer: false },
  voiceReceive: { enabled: false },
  routePlanner: { strategy: 'RotateOnBan', bannedIpCooldown: 600000, ipBlocks: [] },
  rateLimit: { enabled: true, global: { maxRequests: 1000, timeWindowMs: 60000 }, perIp: { maxRequests: 100, timeWindowMs: 10000 }, perUserId: { maxRequests: 50, timeWindowMs: 5000 }, perGuildId: { maxRequests: 20, timeWindowMs: 5000 } },
  dosProtection: { enabled: true, thresholds: { burstRequests: 50, timeWindowMs: 10000 }, mitigation: { delayMs: 500, blockDurationMs: 300000 } },
  metrics: { enabled: false },
  mix: { enabled: false },
  plugins: [],
  pluginConfig: {},
};
