export default {
  server: {
    host: '0.0.0.0',
    port: 2333,
    password: process.env.NODELINK_SERVER_PASSWORD || 'youshallnotpass',
    useBunServer: false,
  },
  cluster: {
    enabled: true,
    workers: 0,
    minWorkers: 1,
    runtime: {
      workerMaxOldSpaceMb: 0,
      workerExposeGc: false,
      workerExecArgv: [],
      sourceWorkerMaxOldSpaceMb: 0,
      sourceWorkerExposeGc: false,
      sourceWorkerExecArgv: [],
    },
    specializedSourceWorker: {
      enabled: false,
      count: 1,
      microWorkers: 1,
      tasksPerWorker: 32,
      silentLogs: true,
    },
    commandTimeout: 6000,
    fastCommandTimeout: 4000,
    maxRetries: 2,
    hibernation: { enabled: true, timeoutMs: 1200000 },
    scaling: {
      maxPlayersPerWorker: 20,
      targetUtilization: 0.7,
      scaleUpThreshold: 0.75,
      scaleDownThreshold: 0.3,
      checkIntervalMs: 5000,
      idleWorkerTimeoutMs: 60000,
      queueLengthScaleUpFactor: 5,
      lagPenaltyLimit: 60,
      cpuPenaltyLimit: 0.85,
    },
    endpoint: {
      patchEnabled: true,
      allowExternalPatch: false,
      code: 'CAPYBARA',
    },
  },
  logging: {
    level: 'info',
    file: {
      enabled: false,
      path: 'logs',
      rotation: 'daily',
      ttlDays: 7,
    },
    debug: {
      all: false,
      request: false,
      session: true,
      player: true,
      filters: false,
      sources: false,
      lyrics: false,
      youtube: true,
      'youtube-cipher': true,
      sabr: false,
      potoken: false,
    },
  },
  connection: {
    logAllChecks: false,
    interval: 300000,
    timeout: 10000,
    thresholds: { bad: 1, average: 5 },
  },
  maxSearchResults: 10,
  maxAlbumPlaylistLength: 100,
  playerUpdateInterval: 2000,
  statsUpdateInterval: 30000,
  trackStuckThresholdMs: 10000,
  eventTimeoutMs: 15000,
  zombieThresholdMs: 60000,
  enableHoloTracks: false,
  enableTrackStreamEndpoint: false,
  enableLoadStreamEndpoint: false,
  resolveExternalLinks: false,
  fetchChannelInfo: false,
  sponsorblock: {
    enabled: false,
    api: 'https://sponsor.ajay.app',
    categories: ['sponsor', 'selfpromo', 'interaction', 'intro', 'outro', 'preview', 'music_offtopic', 'filler'],
    actionTypes: ['skip'],
    skipMarginMs: 150,
  },
  filters: {
    enabled: {
      tremolo: true,
      vibrato: true,
      lowpass: true,
      highpass: true,
      rotation: true,
      karaoke: true,
      distortion: true,
      channelMix: true,
      equalizer: true,
      chorus: true,
      compressor: true,
      echo: true,
      phaser: true,
      timescale: true,
    },
  },
  defaultSearchSource: ['youtube'],
  unifiedSearchSources: ['youtube'],
  sources: {
    youtube: { enabled: true, allowItag: [], targetItag: null, getOAuthToken: false, hl: 'en', gl: 'US', fallbackSources: [], clients: { search: ['Android'], playback: ['AndroidVR'], resolve: ['AndroidVR'], settings: { TV: { refreshToken: [''] } } }, cipher: { url: 'https://cipher.kikkia.dev/api', token: null } },
    http: { enabled: true, userAgent: '' },
    soundcloud: { enabled: false },
    spotify: { enabled: false, clientId: '', clientSecret: '', externalAuthUrl: '', market: 'US', playlistLoadLimit: 1, playlistPageLoadConcurrency: 10, albumLoadLimit: 1, albumPageLoadConcurrency: 5, allowExplicit: true, allowLocalFiles: false, sp_dc: '' },
    applemusic: { enabled: false },
    deezer: { enabled: false },
    bandcamp: { enabled: false },
    tidal: { enabled: false },
    pandora: { enabled: false },
    qobuz: { enabled: false },
    yandexmusic: { enabled: false },
    vkmusic: { enabled: false },
    amazonmusic: { enabled: false },
    anghami: { enabled: false },
    audiomack: { enabled: false },
    audius: { enabled: false },
    bilibili: { enabled: false },
    bluesky: { enabled: false },
    eternalbox: { enabled: false },
    flowery: { enabled: false },
    gaana: { enabled: false },
    googledrive: { enabled: false },
    'google-tts': { enabled: false },
    iheartradio: { enabled: false },
    instagram: { enabled: false },
    jiosaavn: { enabled: false },
    kwai: { enabled: false },
    lastfm: { enabled: false },
    lazypytts: { enabled: false },
    letrasmus: { enabled: false },
    local: { enabled: false },
    mixcloud: { enabled: false },
    monochrome: { enabled: false },
    netease: { enabled: false },
    nicovideo: { enabled: false },
    pinterest: { enabled: false },
    pipertts: { enabled: false },
    reddit: { enabled: false },
    rss: { enabled: false },
    shazam: { enabled: false },
    songlink: { enabled: false },
    telegram: { enabled: false },
    tumblr: { enabled: false },
    twitch: { enabled: false },
    twitter: { enabled: false },
    vimeo: { enabled: false },
  },
  lyrics: { fallbackSource: 'genius', youtube: { enabled: true }, genius: { enabled: false }, musixmatch: { enabled: false }, deezer: { enabled: false }, lrclib: { enabled: false }, letrasmus: { enabled: false }, bilibili: { enabled: false }, yandexmusic: { enabled: false }, monochrome: { enabled: false } },
  meanings: { letrasmus: { enabled: false }, wikipedia: { enabled: false } },
  audio: {
    quality: 'high',
    encryption: 'aead_aes256_gcm_rtpsize',
    resamplingQuality: 'best',
    loudnessNormalizer: false,
    lookaheadMs: 5,
    gateThresholdLUFS: -60,
    fading: { enabled: false, trackStart: { duration: 0, curve: 'linear', type: 'volume' }, trackEnd: { duration: 0, curve: 'linear', type: 'volume' }, trackStop: { duration: 0, curve: 'linear', type: 'volume' }, seek: { duration: 0, curve: 'linear', type: 'volume' }, pause: { duration: 0, curve: 'sinusoidal', type: 'tape' }, resume: { duration: 0, curve: 'sinusoidal', type: 'tape' }, ducking: { enabled: false, duration: 0, targetVolume: 0.3, curve: 'linear' } },
    crossfade: { enabled: false, duration: 0, curve: 'sinusoidal', mode: 'preload', minBufferMs: 250, bufferMs: 0 },
  },
  voiceReceive: { enabled: false, format: 'opus' },
  routePlanner: { strategy: 'RotateOnBan', bannedIpCooldown: 600000, ipBlocks: [] },
  rateLimit: { enabled: true, global: { maxRequests: 1000, timeWindowMs: 60000 }, perIp: { maxRequests: 100, timeWindowMs: 10000 }, perUserId: { maxRequests: 50, timeWindowMs: 5000 }, perGuildId: { maxRequests: 20, timeWindowMs: 5000 }, ignorePaths: [], ignore: { userIds: [], guildIds: [], ips: [] } },
  dosProtection: { enabled: true, thresholds: { burstRequests: 50, timeWindowMs: 10000 }, mitigation: { delayMs: 500, blockDurationMs: 300000 }, ignore: { userIds: [], guildIds: [], ips: [] } },
  metrics: { enabled: false, authorization: { type: 'Bearer', username: 'admin', password: '' } },
  mix: { enabled: false, defaultVolume: 0.8, maxLayersMix: 5, autoCleanup: true },
  plugins: [],
  pluginConfig: {},
};
