server:
  port: ${LAVALINK_SERVER_PORT:-2333}
  address: 0.0.0.0

lavalink:
  server:
    password: "${LAVALINK_SERVER_PASSWORD:youshallnotpass}"
    sources:
      youtube: false
      soundcloud: true
      http: true
      local: false
    bufferDurationMs: 400
    frameBufferDurationMs: 5000
    opusEncodingQuality: 10
    resamplingQuality: HIGH
    trackStuckThresholdMs: 10000
    useSeekGhosting: true
    playerUpdateInterval: 5
    soundcloudSearchEnabled: true
    gc-warnings: true

plugins:
  path: /opt/Lavalink/plugins

metrics:
  prometheus:
    enabled: false
    endpoint: /metrics

logging:
  file:
    path: ./logs/
    maxHistory: 7
  level:
    root: INFO
    lavalink: INFO
